### ISSUE TITLE
links

### ISSUE THREAD

**Issue by nateGeorge** [meagmohit/EEG-Datasets#5]
Thanks for compiling this list.
Your first physionet link goes to the general physionet index; I don't recommend that.  The second physionet link is broken.  Here is one EEG dataset I've used there: https://physionet.org/content/eegmmidb/1.0.0/

This seems to be a compilation of a few as well: https://sccn.ucsd.edu/~arno/fam2data/publicly_available_EEG_data.html

This is another one I've used before:
http://suendermann.com/corpus/EEG_Eyes.arff.gz
from here: http://suendermann.com/su/pdf/aihls2013.pdf

Lastly, not sure if you have KARA ONE: http://www.cs.toronto.edu/~complingweb/data/karaOne/karaOne.html

**Comment by meagmohit** [comment]
Thanks for your comments. 

> Your first physionet link goes to the general physionet index; I don't recommend that. The second physionet link is broken.

The first physionet link which goes to the general physionet index; (I'm assuming you're talking about this one - https://www.physionet.org/data/#neuro) is a generic link for all the datasets provided by the physionet. The filtering and organizing of these datasets demand significant time, and since I'm incapable to filter each and every link, I've put it in the "Unfiltered links" part and keep updating from time to time. I encourage public community to contribute and keep this list compiled.

> The second physionet link is broken. 
Thanks for letting me know. I've updated it. 

https://physionet.org/content/eegmmidb/1.0.0/ 
This link is already available for Motor Imagery (ii)

https://sccn.ucsd.edu/~arno/fam2data/publicly_available_EEG_data.html
- This has been already included in the unfiltered links, for me and others to filter and properly organize when time permits. 

>  This is another one I've used before:
> http://suendermann.com/corpus/EEG_Eyes.arff.gz
> from here: http://suendermann.com/su/pdf/aihls2013.pdf
> Lastly, not sure if you have KARA ONE: http://www.cs.toronto.edu/~complingweb/data/karaOne/karaOne.html

Thanks for bringing these links to my attention. I've added them in unfiltered links.
